### ISSUE TITLE
t/250-register-jsonrpc.t fails (with recent JSON::XS?)

### ISSUE THREAD

**Issue by eserte** [abeltje/Dancer-Plugin-RPC#3]
I see the following failure, probably only with recent JSON::XS versions:

```
hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at (eval 44) line 151, <$fh> line 12.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 1.
t/250-register-jsonrpc.t ...... 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 1 subtests passed 
```

**Comment by abeltje** [comment]
I can't reproduce with the latest Dancer, JSON::XS on 5.18 (mac), perhaps you can provide the output of: ```prove -wlv t/250-register-jsonrpc.t```

-- Abe.

**Comment by eserte** [comment]
I think the report was against 1.00 which had a long fail list: http://fast-matrix.cpantesters.org/?dist=Dancer-Plugin-RPC%201.00
However, the current 1.03 looks much better: http://fast-matrix.cpantesters.org/?dist=Dancer-Plugin-RPC%201.03
So I think the issue is resolved.
